### ISSUE TITLE
Database plan

### ISSUE THREAD

**Issue by ericgeil223** [logan-giese/whiteboard-course-management#10]
Write up a mock up of the data storage plan for the project.

- [x] Create a data design for users (admin / professor / student)
- [x] Create a data design for courses
- [x] Create a data design for assignments and course content (items within a course)

**Comment by logan-giese** [comment]
Depending on who does this task, it may require researching how Firestore databases are organized.  The short version: Data is stored as JSON documents, with no type enforcement, no schema to ensure documents have the same fields, and limited querying.  The flexibility is great, but we need to be careful to define a plan so we don't have mixed-up data.

**Comment by logan-giese** [comment]
Data design for users is complete (as of sprint 3 end).  Next up is courses and assignments/content.

**Comment by logan-giese** [comment]
Data designs for courses and course content / assignments are finished and located in "/docs/database" on the "firestore-services" branch.  Waiting to merge to dev till #37 is finished.
