### ISSUE TITLE
Install NodeJS

### ISSUE THREAD

**Issue by ericgeil223** [logan-giese/whiteboard-course-management#13]
Install NodeJS onto your machine.

**Completed installations:**
- [x] Eric
- [x] Gopi
- [x] Kalkedan
- [x] Logan
- [x] Manik
- [x] Sagar

**Comment by n-grounds** [comment]
Per a discussion in class, the LTS version of NodeJS was indicated as the "right" one to use.

Is this ticket for everyone, how is it being tracked/assigned to ensure everyone has NodeJS installed?

**Comment by n-grounds** [comment]
My question from 7 days ago still stands ... is this ticket for everyone, how is it being tracked/assigned?  Seems it isn't assigned to anyone and is still open.

**Comment by logan-giese** [comment]
I've added a handy-dandy checklist so we can ensure everyone checks off that they installed Node
