### ISSUE TITLE
Create professor version of the assignments page

### ISSUE THREAD

**Issue by ericgeil223** [logan-giese/whiteboard-course-management#51]
Professor should be able to:
 

1. View all assignments that are in a course. 
2. Make new assignments.
3. View student submissions for each assignment per student. 
4. Assign a grade to a student's submission for each assignment.

**Comment by logan-giese** [comment]
Possible duplicate of #62 ?

**Comment by logan-giese** [comment]
This is now the One True Assignments Issue
